import { noul, score } from "@typesafe-ai/sdk";
import { contrast } from "./curve";
import type { AiTellId, AiVerdict } from "./types";

/**
 * "Did an AI write this?" There is no reliable detector, so this is a guess from style, and
 * the UI says so. It follows the Wikipedia "Signs of AI writing" catalogue (also the basis of
 * the humanizer skill): no single tell proves anything, several together are evidence.
 *
 * Jev answers one overall question plus one yes/no per tell. Typography it can't count
 * (dashes, fake bold, arrows, emoji bullets) is measured here in code.
 */

export const AI_QUESTIONS = {
  ai_overall: score(
    "How much does the post read like text generated by an AI assistant such as ChatGPT, rather than written by a person?",
    [
      "Clearly human: personal voice, uneven rhythm, specific details only the author would know.",
      "Probably human, with some polished or generic passages.",
      "Probably AI: smooth, generic and evenly paced, with stock structure.",
      "Clearly AI: template structure, stock phrases, no personal voice at all.",
    ],
  ),
  ai_words: noul(
    "Does the post pile up words typical of AI writing, such as delve, tapestry, testament, pivotal, landscape, underscore, foster, elevate, unlock, navigate, seamless, game-changer, or 'in today's fast-paced world'?",
    {
      true: "Several of these words or phrases appear.",
      false: "None, or just one in passing.",
    },
  ),
  not_x_but_y: noul(
    'Does the post use the pattern "It\'s not X, it\'s Y" or "Not only X, but Y" more than once?',
  ),
  triads: noul(
    "Does the post keep grouping things in threes, like 'innovation, inspiration and impact', as a habit rather than a real list?",
  ),
  fragments: noul(
    "Does the post use rows of short dramatic fragments or slogan-like sayings, like 'No excuses. No shortcuts. Just results.' or 'Data is the new oil'?",
  ),
  fake_candor: noul(
    "Does the post open points with staged candor, like 'Here's the thing', 'Honestly?', 'Let's be real' or 'Hot take:'?",
  ),
  human_details: noul(
    "Does the post contain specific, unusual details or asides only this author would write, such as real names, places, numbers, jokes or mixed feelings?",
  ),
} as const;

/** How much each tell pushes the likelihood up, on top of the overall judgment. */
const MODEL_TELLS = {
  ai_words: 0.3,
  not_x_but_y: 0.25,
  fragments: 0.2,
  fake_candor: 0.2,
  triads: 0.15,
} as const satisfies Partial<Record<AiTellId, number>>;

/**
 * Typography is applied after the human-detail discount: a pasted em dash or 𝗯𝗼𝗹𝗱 text is
 * evidence no matter how specific the rest of the post is.
 */
const TYPOGRAPHY_TELLS = {
  dashes: 0.55,
  fancy_bold: 0.25,
  emoji_bullets: 0.1,
  arrows: 0.1,
} as const satisfies Partial<Record<AiTellId, number>>;

/** The overall judgment alone can reach at most this. */
const OVERALL_SHARE = 0.6;
/** Real human detail can take up to this much off. */
const HUMAN_DISCOUNT = 0.4;
const DEAD_ZONE = 0.15;
const TELL_THRESHOLD = 0.6;

export interface Typography {
  /** Em/en dashes used as punctuation. */
  dashes: number;
  /** The same, per 1,000 characters. */
  dashesPer1k: number;
  /** Characters in Unicode "bold"/"italic" letters, which LinkedIn users paste from generators. */
  fancyChars: number;
  arrows: number;
  /** Lines that start with an emoji used as a bullet. */
  emojiBullets: number;
}

const DASH = /\s[—–]\s|\S—\S/g;
const FANCY = /[\u{1D400}-\u{1D7FF}]/gu;
const ARROW = /[→↳➜➡⇒👉]/gu;
const EMOJI_BULLET = /^\s*\p{Extended_Pictographic}/gmu;

export function typography(text: string): Typography {
  const chars = Math.max(1, text.length);
  const dashes = text.match(DASH)?.length ?? 0;
  return {
    dashes,
    dashesPer1k: (dashes / chars) * 1000,
    fancyChars: text.match(FANCY)?.length ?? 0,
    arrows: text.match(ARROW)?.length ?? 0,
    emojiBullets: text.match(EMOJI_BULLET)?.length ?? 0,
  };
}

/** Each typography tell as 0..1. */
export function typographyTells(t: Typography): Record<keyof typeof TYPOGRAPHY_TELLS, number> {
  const ramp = (x: number, from: number, to: number) =>
    Math.min(1, Math.max(0, (x - from) / (to - from)));
  return {
    // On LinkedIn a spaced em dash is a strong tell: one is half a tell, two are a full one.
    dashes: Math.min(1, t.dashes / 2),
    fancy_bold: ramp(t.fancyChars, 0, 10),
    arrows: ramp(t.arrows, 1, 4),
    emoji_bullets: ramp(t.emojiBullets, 2, 5),
  };
}

type ModelAnswers = Record<keyof typeof MODEL_TELLS | "human_details", number> & {
  /** Overall score normalised to 0..1. */
  overall: number;
};

const clamp01 = (x: number) => (Number.isFinite(x) ? Math.min(1, Math.max(0, x)) : 0);
const beyondDeadZone = (x: number) => Math.max(0, (clamp01(x) - DEAD_ZONE) / (1 - DEAD_ZONE));

export function aiVerdict(answers: ModelAnswers, text: string): AiVerdict {
  const type = typographyTells(typography(text));
  const strength = new Map<AiTellId, number>();

  let modelHuman = 1 - OVERALL_SHARE * clamp01(answers.overall);
  for (const [id, weight] of Object.entries(MODEL_TELLS) as [keyof typeof MODEL_TELLS, number][]) {
    modelHuman *= 1 - weight * beyondDeadZone(answers[id]);
    if (answers[id] >= TELL_THRESHOLD) strength.set(id, answers[id]);
  }
  const model = (1 - modelHuman) * (1 - HUMAN_DISCOUNT * beyondDeadZone(answers.human_details));

  let human = 1 - model;
  for (const [id, weight] of Object.entries(TYPOGRAPHY_TELLS) as [
    keyof typeof TYPOGRAPHY_TELLS,
    number,
  ][]) {
    human *= 1 - weight * type[id];
    if (type[id] >= 0.5) strength.set(id, type[id]);
  }

  return {
    // Same S-curve as the index, so ordinary posts land clearly on one side.
    likelihood: clamp01(contrast(1 - human, 0.45, 8)),
    tells: [...strength.entries()].sort((a, b) => b[1] - a[1]).map(([id]) => id),
  };
}
